# Generated by Django 5.1.2 on 2025-01-16 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_name', models.CharField(blank=True, max_length=255, null=True)),
                ('decoration_name', models.CharField(blank=True, max_length=255, null=True)),
                ('food_items', models.TextField(blank=True, null=True)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchase_date', models.DateField(auto_now_add=True)),
                ('purchase_time', models.TimeField(auto_now_add=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
            ],
        ),
    ]
