# Generated by Django 5.1.2 on 2025-01-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packages', models.TextField()),
                ('price', models.IntegerField()),
                ('dis', models.TextField()),
            ],
        ),
    ]
