# Generated by Django 5.1.2 on 2025-01-07 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_bookings_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='address',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='decoration',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='food',
        ),
        migrations.CreateModel(
            name='DecBookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(null=True)),
                ('phone', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('bookingdate', models.DateField(null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('decoration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.decorations')),
            ],
        ),
        migrations.CreateModel(
            name='Foodbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField()),
                ('bookingdate', models.DateField(null=True)),
                ('time', models.TimeField()),
                ('address', models.TextField(null=True)),
                ('phone', models.IntegerField()),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.catering')),
            ],
        ),
    ]
