# Generated by Django 5.1.2 on 2025-01-02 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_catering'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catering',
            old_name='packages',
            new_name='foods',
        ),
    ]
