# Generated by Django 5.1.2 on 2025-01-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_packages_catering_foods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decorations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.FileField(upload_to='')),
                ('img2', models.FileField(upload_to='')),
                ('img3', models.FileField(upload_to='')),
                ('dis', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
