# Generated by Django 5.1.2 on 2025-01-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_bookings_address_remove_bookings_decoration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodbooking',
            old_name='bookingdate',
            new_name='booking_date',
        ),
        migrations.RemoveField(
            model_name='foodbooking',
            name='food',
        ),
        migrations.AddField(
            model_name='foodbooking',
            name='foods',
            field=models.ManyToManyField(to='app.catering'),
        ),
        migrations.AlterField(
            model_name='foodbooking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
