# Generated by Django 5.1.2 on 2025-01-03 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_halls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.BooleanField()),
                ('video', models.BooleanField()),
                ('both', models.BooleanField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='catering',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.catering'),
        ),
        migrations.AddField(
            model_name='staff',
            name='decoration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.decorations'),
        ),
        migrations.AddField(
            model_name='staff',
            name='status',
            field=models.TextField(default='pending'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='photography',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.camera'),
        ),
    ]
