# Generated by Django 5.1.2 on 2025-01-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(default='message'),
            preserve_default=False,
        ),
    ]
